# Generated by Django 6.1 on 2026-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('filas', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=16)),
                ('categoria_macro', models.CharField(max_length=40)),
                ('subcategoria', models.CharField(blank=True, default='', max_length=120)),
                ('concepto', models.CharField(blank=True, default='', max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
