# Generated by Django 6.1 on 2026-08-21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="motivo",
            field=models.CharField(default="manual", max_length=100),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaccion",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
