# Generated by Django 6.1 on 2026-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campos_temporales'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('usuario', models.CharField(max_length=150)),
                ('expiracion', models.DateTimeField(db_index=True)),
                ('revocado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha', 'tipo'], name='transaccion_fecha_tipo_idx'),
        ),
    ]
