# Generated by Django 6.1 on 2026-08-29 07:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refreshtoken_transaccion_transaccion_fecha_tipo_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos_contactos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastoCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('fecha', models.DateField(db_index=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria_macro', models.CharField(max_length=40)),
                ('subcategoria', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_reparto', models.CharField(choices=[('IGUALES', 'A partes iguales'), ('EXACTO', 'Por cantidad exacta')], default='IGUALES', max_length=16)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pagados', to='api.contacto')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_debido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldado', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='api.contacto')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='api.gastocompartido')),
            ],
            options={
                'unique_together': {('gasto', 'contacto')},
            },
        ),
    ]
