# Generated by Django 6.1 on 2026-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contacto_gastocompartido_participacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocompartido',
            name='mi_parte_saldada',
            field=models.BooleanField(default=False),
        ),
    ]
