# Generated by Django 6.1 on 2026-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gastocompartido_mi_parte_saldada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocompartido',
            name='mi_parte_perdonada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gastocompartido',
            name='mi_parte_saldada_importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='participacion',
            name='importe_saldado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='participacion',
            name='perdonado',
            field=models.BooleanField(default=False),
        ),
    ]
