import { StyleSheet } from "react-native";
import { colors } from "../../theme";

export const dashboardStyles = StyleSheet.create({
  // --- ESTILOS DE DASHBOARD SCREEN ---
  pantalla: { flex: 1, backgroundColor: colors.fondo },
  contenido: {
    padding: 16,
    paddingBottom: 40,
    maxWidth: 1200,
    marginHorizontal: "auto",
    width: "100%",
  },
  centrado: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.fondo,
    padding: 24,
  },
  estadoTexto: { fontSize: 13, color: colors.textoSuave },
  resumenAlcance: {
    fontSize: 11,
    color: colors.textoMuySuave,
    marginBottom: 12,
  },
  heroContainer: {
    alignItems: "center",
    paddingVertical: 30,
    marginBottom: 20,
  },
  heroEtiqueta: {
    fontSize: 14,
    color: colors.textoSuave,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
    textAlign: "center",
  },
  heroValorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  heroValor: {
    fontSize: 48,
    fontWeight: "900",
    color: colors.texto,
    fontVariant: ["tabular-nums"],
    letterSpacing: -1,
  },
  gridPilares: { flexDirection: "column", gap: 16, marginBottom: 24 },
  gridPilaresDesktop: { flexDirection: "row", alignItems: "stretch" },
  gridMetricas: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -6,
    marginBottom: 5,
  },
  metricaTarjeta: { width: "50%", paddingHorizontal: 6, marginBottom: 12 },
  separador: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    marginVertical: 16,
  },
  etiquetaBarra: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.texto,
    marginBottom: 8,
  },
  cabeceraDeudas: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  cajaLiquidez: {
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 12,
    borderRadius: 8,
    gap: 4,
  },
  txtLiquidez: { fontSize: 13, color: colors.textoSuave, fontWeight: "500" },
  filaDeuda: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.02)",
  },
  nombreDeuda: { fontSize: 15, color: colors.texto, fontWeight: "500" },
  valorDeuda: {
    fontSize: 15,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  gridGraficos: { flexDirection: "column", gap: 16 },
  gridGraficosDesktop: { flexDirection: "row", alignItems: "stretch" },

  // --- ESTILOS DE MODAL SALDAR DEUDAS ---
  overlayModalSaldar: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  cajaModalSaldar: {
    backgroundColor: colors.fondo,
    width: "100%",
    maxWidth: 400,
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  cabeceraSaldar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  textoInfoSaldar: {
    fontSize: 15,
    color: colors.texto,
    marginBottom: 20,
    textAlign: "center",
  },
  labelSaldar: {
    fontSize: 12,
    color: colors.textoSuave,
    marginBottom: 6,
    fontWeight: "600",
  },
  inputSaldar: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: colors.bordeFuerte,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 18,
    fontWeight: "600",
    color: colors.texto,
    textAlign: "center",
    marginBottom: 16,
  },
  btnCheckSaldar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  txtCheckSaldar: { fontSize: 13, color: colors.texto, flex: 1 },
  chipCuenta: {
    backgroundColor: colors.fondo,
    borderWidth: 1,
    borderColor: colors.bordeFuerte,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  chipCuentaActivo: {
    backgroundColor: colors.primario,
    borderColor: colors.primario,
  },
  chipCuentaTexto: { fontSize: 13, color: colors.texto, fontWeight: "500" },
  chipCuentaTextoActivo: { color: "#fff", fontWeight: "700" },
  txtNotaGasto: {
    fontSize: 12,
    color: colors.textoSuave,
    fontStyle: "italic",
    marginBottom: 16,
    textAlign: "center",
  },
  btnConfirmarSaldar: {
    backgroundColor: colors.primario,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 10,
  },
  txtConfirmarSaldar: { color: "#fff", fontWeight: "700", fontSize: 15 },
});
